"""Tool 4: generate_report — format the outputs of the other three tools into
a single Markdown compliance briefing, suitable for pasting into a ticket or
sharing with a first-line business team."""
from __future__ import annotations

from datetime import datetime, timezone


def generate_report(
    topic: str,
    search_hits: list[dict],
    cross_reference: dict | None = None,
    gap_analysis: dict | None = None,
) -> str:
    lines = [
        f"# Regulatory Compliance Briefing — {topic}",
        "",
        f"_Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        "> Generated by an AI research assistant over a curated demo corpus. "
        "Verify every citation against the official source before acting on it.",
        "",
        "## Relevant Clauses",
    ]

    if not search_hits:
        lines.append("No relevant clauses were found in the indexed corpus.")
    else:
        for hit in search_hits:
            lines.append(f"- **{hit['citation']}**\n  > {hit['text'].strip()}")

    if cross_reference:
        lines += ["", "## Cross-Regime Overlap"]
        if cross_reference["multi_regime_overlap"]:
            lines.append(
                f"This topic is addressed across {cross_reference['documents_covered']} "
                "separate regulatory documents — check for the strictest applicable "
                "obligation across regimes:"
            )
            for doc, clauses in cross_reference["by_document"].items():
                clause_names = ", ".join(c["clause"] for c in clauses)
                lines.append(f"- **{doc}**: {clause_names}")
        else:
            lines.append("No cross-regime overlap detected for this topic.")

    if gap_analysis:
        lines += ["", "## Gap Analysis"]
        lines.append(gap_analysis["gap_analysis"])
        if gap_analysis["citations"]:
            lines.append("")
            lines.append("**Citations considered:** " + "; ".join(gap_analysis["citations"]))

    return "\n".join(lines)
